spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: shock
    url: jdbc:postgresql://130.162.157.215:5432/shock
    password: "Kth973897G@#$"
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
server:
  port: 9090
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
